# Generated by Django 4.2.5 on 2023-09-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_1',
        ),
        migrations.AddField(
            model_name='product',
            name='name_2',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
